---
- name: Configure login banner
  hosts: cisco
  gather_facts: False
  tasks:
    - name: Configure login banner on Cisco IOS
      ios_banner:
        banner: login
        text:
                 
         This is a test login banner for class4, exercise4.


         Configure via Ansible

        
       
        state: present
      notify: write mem


  handlers:
    - name: write mem
      ios_command:
        commands: write me
      changed_when: True
      
  
        
  
